siteName: "GM Group"
siteTagline: "A diversified enterprise in Dar es Salaam, Tanzania."
contactEmail: "info@gmltzs.com"
contactPhone: "+255713879876"
contactFax: "+255736270605"
address: |
  Kinondoni, Kawawa Road / Kasaba Street
  P.O. Box 452, Dar es Salaam, Tanzania
headOfficeMapEmbed: "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d3961.8346546822513!2d39.263056!3d-6.789965!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNsKwNDcnMjMuOSJTIDM5wrAxNScwMC4wIkU!5e0!3m2!1sen!2stz!4v1775757408690!5m2!1sen!2stz"
socials: []
footerTagline: |
  GM Group
  Building businesses. Creating legacies.
footerLegal: "© 2026 General Malick Limited. All rights reserved."
